import Head from "next/head";
import ErrorBoundary from "../ErrorBoundary/ErrorBoundary";
import Footer from "../Footer/Footer";
import Navigation from "../Navigation/Navigation";
import ErrorFallback from "../ErrorFallback/ErrorFallback";

export default function Skeleton({ title, content }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ErrorBoundary FallbackComponent={ErrorFallback}>
        <Navigation />
      </ErrorBoundary>

      <main>{content}</main>

      <ErrorBoundary FallbackComponent={ErrorFallback}>
        <Footer />
      </ErrorBoundary>

      {/* Popups */}
    </>
  );
}
